
[general]

	[general.general]
		draw_waypoint = true
		low_health_alert = 0.19615385
		abiphone_blocker = false
		remove_selfie_mode = true

	[general.timer]
		reminder_text = ""
		reminder_time = 0

	[general.stats]
		show_speed = true

	[general.party]
		enable_whitelist_rejoin = true
		party_chat_command = true
		leader_chat_command = true
		auto_join_reparty = true

[crimson_isles]

	[crimson_isles.crimson_isles]
		golden_fish_timer = false
		broken_hyperion = true
		ragnarok_detection = true

	[crimson_isles.vanquisher_alert]
		vanquisher_detection_sound = false
		vanquisher_auto-warp = ""
		vanquisher_detection = true
		announce_vanquisher = false
		"announce_vanquisher_[act]" = false
		vanquisher_alert = true
		"vanquisher_alert_(all_chat_toggle)" = false

	[crimson_isles.vanquisher_counter]
		vanquisher_counter = true

[hub]

	[hub.inquisitor]
		announce_inquisitor = false
		"announce_inquisitor_(all_chat_toggle)" = false
		detect_inquisitor = false
		"announce_inquisitor_[act]" = false

	[hub.diana]
		diana_warp = false
		diana_waypoint = false

	[hub.griffin_burrow]
		burrow_chat_alert = false
		burrow_amogus_alert = false
		burrow_detection = false

[kuudra]

	[kuudra.kuudra]
		kuudra_hp_display = true
		kuudra_reparty = "bananathebot"
		show_supply_piles = true
		"show_supply/fuel_waypoints" = true
		cells_alignment_timer = true
		kuudra_spawn = true

	[kuudra.kuudra_alert]
		mount_ballista_alert = true
		cannonear_ign = ""
		kuudra_alerts = true
		unready_alert = true
		kuudra_alert_options = false
		stun_alert = true
		token_alert = 238
		fresh_tools_alert = true
		no_key_alert = true
		choose_route_alert = true
		fuel_percent_alert = true
		stunner_ign = ""
		pickup_supply_alert = true
		"kuudra_alerts_(cannonear_ign)" = ""
		stunner_eaten_alert = true
		building_alert = true
		dropship_alert = true
		"kuudra_alerts_(stunner_ign)" = ""

	[kuudra.kuudra_splits]
		kuudra_splits = true

[garden]

	[garden.garden]
		garden_tab_display = true
		composter_alert = true

